### PR TITLE
Scalajs 1.8.0

### PR DESCRIPTION
**Pull request by sjrd**

### CODE REVIEW

**Comment by sjrd** [comment]
Ping @gzm0 :)

**Comment by gzm0** [comment]
Thanks for the ping. This indeed slipped through the cracks.

There seems to be a lot in 1.8.0, so I'll for sure need until the end of the day to review this fully.

**Comment by sjrd** [comment]
Sure, no problem. :) There's no rush.

**Review by gzm0 — APPROVED** [review]
Just minor typos.

**Comment by sjrd** [comment]
Thanks :)

**Pull request merged**
