### PR TITLE
Fix the style.css file so that it is not binary.

### PR DESCRIPTION
**Pull request by sjrd**
sed -e 's/\x00\x00/ /'

### CODE REVIEW

**Comment by sjrd** [comment]
Review by @ochrons

**Comment by ochrons** [comment]
Github still shows it to me as binary, but maybe that's because of diffing to the old one?

Anyway, this is "rewritten" in my latest PR.

**Comment by sjrd** [comment]
Yes it's the diff. If you click on View it shows it as text, now.

I saw that it's rewritten in your PR. Merging this one first would at least show the other rewrite as a Move instead of a file coming out of the blue. As you wish.

**Comment by ochrons** [comment]
I would just drop this, as the new version has the (S)CSS file in a different location (due to asset bundling) and with a different extension and basically every line is touched due to changes and cleanup.

**Comment by sjrd** [comment]
OK.

**Pull request closed without merging**
