### PR TITLE
Announcing Scala.js 0.6.0-RC1.

### PR DESCRIPTION
**Pull request by sjrd**

### CODE REVIEW

**Comment by sjrd** [comment]
Hopefully to be announced on Monday 12.

**Comment by sjrd** [comment]
/cc @lihaoyi @alexandru 
I just published 0.6.0-RC1 on Sonatype. I plan to announce this release on Monday 12. If you have some time to publish your libraries and testing frameworks, that'd be great :) AFAICT, compared to M3 it shouldn't be more than changing the Scala.js version number. Everything should be source compatible.

**Comment by sjrd** [comment]
DOM and jQuery 0.7.0 are published.

**Comment by sjrd** [comment]
JavaDoc published.

**Comment by lihaoyi** [comment]
I'm having to `clean` before building otherwise it fails with some sjsir error. Just FYI in case anyone else sees this

**Comment by sjrd** [comment]
That's usually the case when one upgrades the Scala.js version. I'm surprise you never ran into this before.

**Comment by lihaoyi** [comment]
I've published the following versions all built against 0.6.0 RC1, which should end up on maven central any time now:

```scala
"com.lihaoyi" %%% "autowire" % "0.2.4-RC1"
"com.lihaoyi" %%% "scalatags" % "0.4.3-RC1"
"com.lihaoyi" %%% "scalarx" % "0.2.7-RC1"
"com.lihaoyi" %%% "upickle" % "0.2.6-RC1"
"com.lihaoyi" %%% "utest" % "0.2.5-RC1"
```

All tests pass in fastOpt and fullOpt. Note how I've normalized all the organizations to `"com.lihaoyi"`, instead of `"com.scalatags"` or `"com.scalarx"`.

**Comment by sjrd** [comment]
Awesome. I have updated the announcement, as well as the [0.6.x branch of the tutorial](https://github.com/scala-js/scalajs-tutorial/tree/0.6.x).

**Comment by gzm0** [comment]
LGTM (I did not look at the tutorial)

**Pull request merged**
