### PR TITLE
Gabriel Bezerra's picture and position at the testimonials

### PR DESCRIPTION
**Pull request by gabriel-bezerra**

### CODE REVIEW

**Comment by gabriel-bezerra** [comment]
Thank you.

**Comment by sjrd** [comment]
Could you make the commit message a little bit less dependent on who is "I"? I suggest:

    Add @gabriel-bezerra's picture and position in the testimonials.

**Comment by gabriel-bezerra** [comment]
Done.

**Comment by sjrd** [comment]
LGTM

**Comment by gabriel-bezerra** [comment]
Thank you, Sébastien and Otto.

**Pull request merged**
