### PR TITLE
Add dockerized example app to list of open source projects. Spelling …

### PR DESCRIPTION
**Pull request by mb720**
…and grammar corrections on community site.

### CODE REVIEW

**Comment by sjrd** [comment]
I'm wondering whether this shouldn't be on the [Project skeletons](https://www.scala-js.org/libraries/skeletons.html) page instead?

**Comment by mb720** [comment]
I agree.

If it's fine with you, I'll close this PR and create a new one that will include the spelling corrections for the community page and the link to the example app for the skeleton page.

**Comment by sjrd** [comment]
Sure.

**Comment by mb720** [comment]
Alright, I moved the link to the skeleton page.
I think it's easier to not close this PR and create a new one as I suggested above.
If it looks good to you, you can merge it.

**Pull request merged**
