### PR TITLE
Add link to scalajs-benchmark

### PR DESCRIPTION
**Pull request by japgolly**

### CODE REVIEW

**Comment by sjrd** [comment]
Since we're in the process of moving to the new website, I'm not merging anything at the moment.

**Comment by japgolly** [comment]
No worries. Looking forward to the new site!

**Comment by sjrd** [comment]
Now that the new website is live, could you retarget this to the new master, please?

**Comment by japgolly** [comment]
@ochrons @sjrd I'm not sure where I would add scalajs-benchmarks. We don't have a page for libraries that are for Scala.JS only (not Scala) and are not JS facades.

My first thought was maybe we should rename "Scala libraries" to "Scala & Scala.JS libraries" and then add "Scala.JS exclusive libraries"...

...but then I thought, as a user looking for a library, you don't care right? A user would likely have a genre in mind like "performance" or "tools" or "serialisation". Thoughts?

**Comment by ochrons** [comment]
I would put this under Scala libraries for now. When we have more libs, we can fork it into more specific lists.

**Comment by japgolly** [comment]
Resubmitted in #213

**Pull request closed without merging**
