### PR TITLE
static types for google maps v3

### PR DESCRIPTION
**Pull request by coreyauger**
Add scalajs-google-maps: static types for Google Maps v3.

### CODE REVIEW

**Comment by sjrd** [comment]
OK, could you just amend the commit message so that it's something like

> Add scalajs-google-maps: static types for Google Maps v3.

Note the capital and imperative "Add" as well as the ending dot.

**Comment by coreyauger** [comment]
done.

**Comment by sjrd** [comment]
> done.

Hum did you? I don't see anything changed. I still see "static types for google maps v3" as the commit message.
Did you forget to `git push --force`, maybe?

**Comment by coreyauger** [comment]
sorry I have now done a 
git commit --amend -m "Add scalajs-google-maps: static types for Google Maps v3."

**Comment by sjrd** [comment]
Ah, somehow it all went wrong, and there's now a weird double commit + merge commit. Never mind, I'll fix it locally and push.

**Comment by sjrd** [comment]
OK done. Thanks, and sorry for the fuss.

**Pull request closed without merging**
