### PR TITLE
Condense and organize the list of libraries.

### PR DESCRIPTION
**Pull request by sjrd**
The list of libraries has become too big and too random. This hopefully makes it more useful by categorizing the libraries, and only providing one-line descriptions. sbt details should be found on the libraries' respective readmes.

### CODE REVIEW

**Comment by sjrd** [comment]
Review by @lihaoyi and all who want to.

**Comment by jducoeur** [comment]
Makes sense to me...

**Comment by gzm0** [comment]
LGTM

**Comment by japgolly** [comment]
Excellent. Something like this needed doing. :+1:

**Comment by lihaoyi** [comment]
Looks good to me. We could definitely use a new website, if anyone's up for some web-design. e.g. look at the websites other people have:

- https://www.dartlang.org/
- http://www.typescriptlang.org/
- http://kotlinlang.org/

Compared to ours, they seem to provide:

- So material design
- Much responsive
- Very gradients
- Wow

**Pull request merged**
