### PR TITLE
Scala.js beyond the browser

### PR DESCRIPTION
**Pull request by armanbilge**
Inspired by this blurb on the Scala Center "First Five Years" report.

> Scala.js targets any JavaScript environment, from browsers to Node.js servers to embedded devices. Using Scala.js, developers can leverage Scala, its libraries, as well as the JavaScript ecosystem, to develop robust applications that run anywhere.

https://scala.epfl.ch/records/first-five-years/report#tech

I attempted to condense it. Here's a couple proposals. feedback and revisions very welcome, etc. etc. :)

> Harness the Scala and JavaScript ecosystems to develop robust apps. Rrun in browsers, serverless, Node.js. Anywhere.

Screen Shot 2023-03-07 at 3 59 48 PM

> Harness the Scala and JavaScript ecosystems together. Develop robust apps that run in browsers, serverless, Node.js. Anywhere.

Not sure how important this "anywhere" is 🤔 

Thanks!

### CODE REVIEW

**Comment by sjrd** [comment]
The "Anywhere" alone in its sentence feels odd. And "serverless" doesn't sound right to me as a "place" for things to run on. Perhpas

Harness the Scala and JavaScript ecosystems together.
Develop robust apps that run anywhere:
from browsers to Node.js servers to serverless something-something.

**Comment by armanbilge** [comment]
> And "serverless" doesn't sound right to me as a "place" for things to run on.

Sure, technically we want to say "serverless platforms" or "serverless runtimes" or something like that. But it feels unnecessarily verbose IMHO, "serverless" is good enough to get the meaning across.

I like your suggestion!



Here it is with less words.



And here's a variation that drops "anywhere" and is even shorter.

**Comment by armanbilge** [comment]
Sorry, one more :)

**Comment by sjrd** [comment]
The current favorite seemed good enough not hold this up any longer ;)

**Pull request merged**
