### PR TITLE
Website 2.0

### PR DESCRIPTION
**Pull request by ochrons**
Ready to go live?

### CODE REVIEW

**Comment by gzm0** [comment]
OMG +16'241, -2'507

**Comment by sjrd** [comment]
I think, instead of reviewing this PR here, I will send PRs of my own to your repo. It will be easier, I think.

**Comment by gzm0** [comment]
Is http://ochrons.github.io/sjs2/ up to date?

**Comment by ochrons** [comment]
No, I've made some (minor) changes that are not in the sjs2 version. Content-wise they are pretty much identical, though.

**Comment by sjrd** [comment]
About to go LIVE!!!

**Comment by gzm0** [comment]
Woooot

**Pull request merged**
