### PR TITLE
Add Each library

### PR DESCRIPTION
**Pull request by Atry**
Recently I released Each library for Scala.js https://repo1.maven.org/maven2/com/thoughtworks/each/each_sjs0.6_2.11/0.4.2/

``` sbt
libraryDependencies += "com.thoughtworks.each" %%% "each" % "0.4.2"
```

### CODE REVIEW

**Comment by sjrd** [comment]
Thanks. We're currently in a week of transformation to the new website (see #177), so I'm not merging any PR right now. I will add your library to the new website.

**Comment by sjrd** [comment]
Now that the new website is live, could you please retarget this on the new master. (It is probably easier to just create a new branch off master.) The file to edit is https://github.com/scala-js/scala-js-website/blob/master/_data/library/scalalibs.yml

**Comment by Atry** [comment]
The new PR is at #191

**Comment by sjrd** [comment]
Superseded by #191

**Pull request closed without merging**
