### PR TITLE
Update the tutorial for DOM and jQuery 0.9.0.

### PR DESCRIPTION
**Pull request by sjrd**
New commit history for the tutorial repo available at https://github.com/scala-js/scalajs-tutorial/commits/develop

### CODE REVIEW

**Comment by sjrd** [comment]
Review by @nicolasstucki 
/cc @mseddon

**Comment by ochrons** [comment]
You should also update the `_data/library/jsfacades.yml` file with new versions.

**Comment by sjrd** [comment]
Done.

**Comment by nicolasstucki** [comment]
LGTM

**Comment by mseddon** [comment]
LGTM also.

**Pull request merged**
