### PR TITLE
Insert reference to new skeleton, play-scalajs-workbench-example

### PR DESCRIPTION
**Pull request by aholland**
PR created as per Otto Chrons' suggestion on https://gitter.im/scala-js/scala-js:
"**ochrons Mar 17 07:26** @aholland you should raise an issue/PR on scala-js-website to get that included on the site".

My concerns are
(1) Why does the other reference to Play (directly above mine) have an exclamation mark? Should mine also, or show that one not be there, or don't we care?
(2) Is my explanation too long?

Thanks,
Anthony

### CODE REVIEW

**Comment by sjrd** [comment]
(1) I'm pretty sure Play's "official" name was "Play!", but apparently their website does not write it like this anymore.
(2) It's a bit long, yes. I suggest stopping after the first period.

**Comment by aholland** [comment]
I think it's important to mention the basic reason for having the workbench-style setup, so I've constructed a one sentence explanation which does that.

**Comment by sjrd** [comment]
OK. Could you squash all the commits into one, and force-push on the branch, please?

**Comment by aholland** [comment]
Done, I believe...

**Comment by sjrd** [comment]
LGTM

**Comment by aholland** [comment]
Thanks Sébastien.

**Pull request merged**
