### PR TITLE
Add scalajs-jsjoda.

### PR DESCRIPTION
**Pull request by rpiaggio**

### CODE REVIEW

**Comment by sjrd** [comment]
Thanks. I suggest you only mention `scalajs-jsjoda` in the facade list, but that you add `scalajs-jsjoda-as-javatime` as a separate entry in the "JDK extensions" section of https://github.com/scala-js/scala-js-website/blob/master/_data/library/scalalibs.yml

IMO that would be more appropriate.

**Comment by sjrd** [comment]
Oh and, [we do not accept PRs from the master branch](https://github.com/scala-js/scala-js/blob/master/CONTRIBUTING.md#pull-request-requirements). Since it is not possible to change the branch of a PR, I will close this PR. Please reopen a separate PR from a different branch. Sorry for the inconvenience.

**Comment by rpiaggio** [comment]
Ok, sorry about that! I will modify as you suggest and do a new PR.

**Comment by rpiaggio** [comment]
https://github.com/scala-js/scala-js-website/pull/290

**Pull request closed without merging**
