### PR TITLE
Add a pointer to NodeListSeq in scalajs-dom.

### PR DESCRIPTION
**Pull request by bbarker**

### CODE REVIEW

**Comment by sjrd** [comment]
Could you rebase your branch on top of master to receive the fix from #396, please?

**Comment by bbarker** [comment]
@sjrd I can, but first, just to check - since I did this directly on github, I recently discovered there is a rebase and merge option on github - next to the merge button there should be a drop down. Sorry if I'm pointing out the obvious.

**Comment by sjrd** [comment]
The problem is that it doesn't quite guarantee that your commit itself would indeed build once rebased. But no worries, I'll rebase it for you.

**Comment by bbarker** [comment]
Ah, I see, should have thought of that - thanks!

**Pull request merged**
