### PR TITLE
Separated libraries under a new section in top menu.

### LINKED ISSUE #185: Easier access to libraries (top level menu item)?
From Gitter:

But where is the list of SJS wrappers in the new website?
That was one of the most useful parts in the last one

sjrd 12:17:
http://www.scala-js.org/community/libraries/
How did you search for it? Where were you expecting to see links to it that you did not find?

mkotsbak 12:18
A bit hidden. I looked at "community", but did not notice the menu on the right
What about a "LIBRARIES" top level menu?

sjrd 12:27
We could do that, yes.

ochrons 12:33
yea, the Community is a bit abstract, so Libraries top item would be good
although that then leaves the community part quite bare 

mkotsbak 12:33
No, I don't think so. It contains what you expect to find there
libs was 0 clicks in old webiste, so it should not be more than 1 click in the new
Actually it is two as there are sections
Sections could be dropdown menu or filters

### PR DESCRIPTION
**Pull request by ochrons**
Fixes #185

### CODE REVIEW

**Comment by sjrd** [comment]
OK but you have to adapt `/.htaccess` to to set up the appropriate redirects.

**Comment by sjrd** [comment]
Is `_includes/css/style.css` an accident? What does this do in this PR?

**Comment by ochrons** [comment]
For some reason Github considers it a binary file, even though it's just a normal CSS file. It may contain some extra \0 characters or something, but it has been like that for awhile.

I'm actually fixing that in my perf opt branch at the moment, with a lot of other changes to the build process.

**Comment by sjrd** [comment]
My question is rather why it appears in *this* PR. It does not seem like there should be any change to the CSS, should it?

**Comment by ochrons** [comment]
There was a minor update to the CSS as well, to squeeze the top headings closer to each other so they would fit on a single line in medium size.

**Comment by sjrd** [comment]
LGTM, OK.

**Pull request merged**
