### PR TITLE
Added link to Paths.scala.js

### PR DESCRIPTION
**Pull request by andreaferretti**
I hope this is the right way to submit a link for new libraries. :-)

Since it did not exist, I have created the category `Visualization` just below `UI frameworks`

### CODE REVIEW

**Comment by sjrd** [comment]
I would just put this section between Client-server com and FRP. It has less applicability than serialization and client-server com, IMO.

**Comment by andreaferretti** [comment]
Done. I had put it near UI frameworks just by analogy, not importance.

**Comment by sjrd** [comment]
OK, could you just squash the commits, please?

**Comment by andreaferretti** [comment]
I will have to close this PR. I will open another one with the squashed history

**Pull request closed without merging**
